services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kips_chatbot_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
      
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-pg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kips_chatbot_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  pgvector-data:
    